GET http://localhost:3001/blocks

###

POST http://localhost:3001/mine
Content-Type: application/json

{
    "data":"None"
}

###

GET http://localhost:3002/blocks

###

POST http://localhost:3002/mine
Content-Type: application/json

{
    "data":"None"
}
